version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.5
    working_directory: ~/d10
    steps:
      - checkout
      - run:
          shell: /bin/sh
          command: |
            composer install
            pwd
            ls -al web/modules/contrib